---
title: "Lab02"
author: "Amran A"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

#Importing all datasets
```{r}

library(tidyverse)

#importing my datasets
data2015 <- read.csv("2015_ontario_public_library_statistics_open_data_dec_2017rev.csv")

data2016 <- read.csv("2016 ontario_public_library_statistics_open_data_2016.csv")

data2017 <- read.csv("2017 ontario_public_library_statistics_open_data_july_2019_rev1.csv")

```


#Creating an object that merges all the files into one object
```{r}
#organizing my column names
common_columns <- Reduce(intersect, list(colnames(data2015),colnames(data2016),colnames(data2017)))

#combining my files data
datacombined <- rbind(subset(data2015, select = common_columns), subset(data2016, select = common_columns), subset(data2017, select = common_columns))

#removing the commas in values from combined data
as.numeric(gsub(",", "", datacombined, fixed = TRUE))


#removing NA's
na.omit(datacombined)

#removing any spaces in variable names
names(datacombined) 

```


#Creating a single dataset that can be used to output a table listing the number of libraries in each city for years

```{r}

library(dplyr)

#reordering data so that list is in order of years
datacombined1 <- datacombined[order(datacombined$Survey.Year.From),]

view(datacombined1)

#table with the frequency of city names listed, every year.
library_city <- table(datacombined1$A1.10.City.Town, datacombined1$Survey.Year.From)

#Since the data is listed for every library in Ontario, the frequency of a specific city showing up would be the same as the amount of libraries in that city for each year
view(library_city)

#Renaming the City and Year column names in table from Var1 and Var2
colnames(library_city)[colnames(library_city) == "Var1"] = "A1.10.City.Town"
colnames(library_city)[colnames(library_city) == "Var2"] = "Survey.Year.From"

```


#Code that shows the total number of active cardholders for each library 
```{r}

#number of cardholders for every library
total_cardholders <- select(datacombined,Library.Full.Name,A1.14..No..of.Active.Library.Cardholders,Survey.Year.From)


```


#Code listing the top 5 libraries with the highest average Total Operating Revenues
```{r}
library(dplyr)

#Putting library name and revenue variables together 
Revenue <- select(datacombined,Library.Full.Name,B2.9..Total.Operating.Revenues)

#Removing commas
as.numeric(gsub(",", "", Revenue , fixed = TRUE))

#removing NA's
na.omit(Revenue)

#Reorder revenue in data
OrderByRevenue <- Revenue[order(Revenue$B2.9..Total.Operating.Revenues),]

#Selecting first or top five libraries in the list
Top_Five_Revenue <- OrderByRevenue %>%
  slice(1:5)


```

